### PR TITLE
README.md

### PR DESCRIPTION
**Pull request by ali-cloudy**

### CODE REVIEW

**Review by drunkleen — APPROVED** [review]

**Review by drunkleen — COMMENTED** [review]
I find it unclear why the name and link for the live web app need to be altered. It seems evident that the provided link directs to your repository and not the live version of the app.

**Review by drunkleen — COMMENTED** [review]
Here, you referenced the alterations in the README.md file rather than documenting them in your Git commit information.

**Comment by drunkleen** [comment]
Thanks for your commit to the repo

**Comment by ali-cloudy** [comment]
Your welcome . My will was to edit and develope your repo by some issues couldn't it happened. Like add a field that user can upload a txt file with 200 uuids in rach file and specific extra parameters that should be add in your web app like tcp delay . Xudp and exactly what is xudp . Is there in Iran work in our communication internet network 🛜?! And a second page that users can put a word or a specific sentence in find field and choose a file instead replace field or a word or a a file that must be split and each of it can be in one of created vl/vmess configs in previous my ask that was creates any configs with web app and generate uuid by Ubuntu . I want edit it about next week . I know this is Hugh and needs some help if I will run it in attached future my man.

**Comment by drunkleen** [comment]
Thank you for your message and your willingness to contribute to the development of my repository. I appreciate your input and ideas for enhancing the functionality of the web app. Regarding XUDP, it stands for Extended UDP, which is an API for extended UDP networking.

Currently, I'm facing some time constraints due to work commitments, but I'm open to collaboration and assistance. If there are specific areas or features in the repository that you'd like help with, please let me know, and I'll do my best to guide or contribute when time permits. Your suggestions for adding a field to upload a txt file with UUIDs, along with additional parameters, sound interesting, and I'd be happy to discuss further details.

Feel free to share more details about the specific issues you encountered so that we can work together on resolving them. Thank you again for your interest and willingness to contribute, and I look forward to collaborating with you in the near future.

**Pull request merged**
